name: Build and Release Skeleton Editor

on:
  push:
    tags:
      - 'v*'  # 当推送以v开头的标签时触发
  workflow_dispatch:  # 允许手动触发

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'
  PROJECT_PATH: 'SkeletonEditor/SkeletonEditor.csproj'

jobs:
  build:
    runs-on: windows-latest
    
    # 添加权限设置
    permissions:
      contents: write  # 关键修复：允许创建Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录以访问标签

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build solution
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish application
        run: dotnet publish ${{ env.PROJECT_PATH }} -c ${{ env.BUILD_CONFIGURATION }} -o ./publish --no-build

      - name: Extract version
        id: get_version
        shell: pwsh
        run: |
          # 从标签获取版本 (格式 v1.2.3)
          $tag_version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          echo "version=$tag_version" >> $env:GITHUB_OUTPUT
          echo "Using tag version: $tag_version"

      - name: Create release artifact
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          Compress-Archive -Path ./publish/* -DestinationPath "SkeletonEditor-$version.zip"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkeletonEditor
          path: SkeletonEditor-*.zip

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1  # 使用更可靠的Release Action
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref_name }}
          name: Skeleton Editor v${{ steps.get_version.outputs.version }}
          body: "Auto-generated release for Skeleton Editor"
          files: |
            SkeletonEditor-*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}