name: Build Skeleton Editor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'
  SOLUTION_PATH: 'SkeletonEditor/SkeletonEditor.sln'
  PROJECT_DIR: 'SkeletonEditor/SkeletonEditor'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      
    - name: Publish application
      run: dotnet publish ${{ env.PROJECT_DIR }} -c ${{ env.BUILD_CONFIGURATION }} -o ./publish --no-build
      
    - name: Extract version
      id: version
      shell: pwsh
      run: |
        $version = (Get-Item ./publish/SkeletonEditor.exe).VersionInfo.FileVersion
        echo "::set-output name=version::$version"
        
    - name: Create release artifact
      run: Compress-Archive -Path ./publish/* -DestinationPath SkeletonEditor-${{ steps.version.outputs.version }}.zip
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SkeletonEditor
        path: SkeletonEditor-*.zip
